### ISSUE TITLE
Support qps and burst of kube api in client-go through command parameters

### ISSUE THREAD

**Issue by whitebear009** [kubernetes-sigs/custom-metrics-apiserver#105]
In some frequently queried scenarios, such as hpa, the default api qps of client-go is relatively small, which will lead to frequent client-side throttle.

We can support qps and burst of kube api in client-go through command parameters.

**Comment by dgrisonnet** [comment]
This sounds reasonable to me, would you be interested in sending a PR to add this feature?

**Comment by whitebear009** [comment]
@dgrisonnet  I am glad that. Here is the PR: https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/121
Please take a look.

**Comment by olivierlemasle** [comment]
Closed with #121 - thanks @whitebear009!
/close
