### ISSUE TITLE
Document metrics exposed by the library

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes-sigs/custom-metrics-apiserver#134]
We should add a documentation that would easily be consumable by our users.

We could do something similar to Kubernetes in https://kubernetes.io/docs/reference/instrumentation/metrics/ and reuse their static analysis tool that generates the doc.

**Comment by dashpole** [comment]
/triage accepted
@olivierlemasle are you still interested in taking this on?

**Comment by hjet** [comment]
@dashpole happy to grab this one, will have time to work on this in the coming days. i'll aim to follow the approach described above by @dgrisonnet

**Comment by hjet** [comment]
so from what i can tell, only [one metric](https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/master/pkg/apiserver/metrics/metrics.go#L28) is exposed by this library. 

would it be okay to create a doc (manually) in `docs/` following the same structure as [this doc](https://kubernetes.io/docs/reference/instrumentation/metrics/), or should i write a quick script to copy the tool and run it on this repo?
