### ISSUE TITLE
resClient.List should add resourceVersion=0 parameter

### ISSUE THREAD

**Issue by xiaomudk** [kubernetes-sigs/custom-metrics-apiserver#154]
resourceVersion=0 is not specified here, causing apiserver to skip the cache and go directly to etcd to read the data.
add resourceVersion=0 parameter, apiserver will read data from the cache, and there is an order of magnitude performance improvement.

**Comment by dgrisonnet** [comment]
I don't think that's something we want to do since it might be hitting stale data from the cache.

**Comment by dashpole** [comment]
/close
based on https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/154#issuecomment-1705572167
