### ISSUE TITLE
[Feature request]  Provide  binary/image

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/custom-metrics-apiserver#159]
Can we provide a binary/image that simulates the APIs maintained by the repository that can be used by e2e to test components that rely on those APIs and provide a good command example for custom-metrics-apiserver?

**Comment by dgrisonnet** [comment]
For e2e test purposes, you could perhaps create a git submodule based on this repo and reuse the test-adapter that we have for our e2e tests.

Another option could be to add a new e2e test package to the library that would provide function to create and deploy a test-adapter.

Other than that, I don't think we should publish the binary or the image publicly since this is only meant for tests purposes.

**Comment by wzshiming** [comment]
You're right.

In fact, this requirement stems from the need to use kwok to simulate scheduling based on GPU utilization, which [I've actually tried to implement in kwok](https://github.com/kubernetes-sigs/kwok/pull/775/commits/2291e20d36b4c28cb6061d12e6979ae2758c4fb4), but it's beyond the scope of kwok.

If we create a new project that has only two CRDs to simulate the values of the [custom metrics](https://github.com/kubernetes-sigs/kwok/blob/2291e20d36b4c28cb6061d12e6979ae2758c4fb4/pkg/apis/v1alpha1/custom_metrics_types.go) and the [external metrics](https://github.com/kubernetes-sigs/kwok/blob/2291e20d36b4c28cb6061d12e6979ae2758c4fb4/pkg/apis/v1alpha1/external_metrics_types.go). What do you think?

**Comment by dgrisonnet** [comment]
That this seems very much out of scope for a project such as kwok. I would expect kwok users to install an existing adapter such as [keda](https://github.com/kedacore/keda) or [prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter) and then collect their GPU metrics in Prometheus or a supported Keda scaler for autoscaling.

> If we create a new project that has only two CRDs to simulate the values of the [custom metrics](https://github.com/kubernetes-sigs/kwok/blob/2291e20d36b4c28cb6061d12e6979ae2758c4fb4/pkg/apis/v1alpha1/custom_metrics_types.go) and the [external metrics](https://github.com/kubernetes-sigs/kwok/blob/2291e20d36b4c28cb6061d12e6979ae2758c4fb4/pkg/apis/v1alpha1/external_metrics_types.go). What do you think?

The HPA controller will not be aware of these resource so autoscaling will not work. Today you have to implement the different metrics API endpoint to serve metrics to the autoscaler.

**Comment by wzshiming** [comment]
I prepared a proposal for a new project and made the implemented code into a standalone project for demonstration purposes.

proposal: https://docs.google.com/document/d/1riVe6W5E9LzE_bZy39wKy5BoSYhVvdKs8zmW4SMh65Y/edit?usp=sharing

demo: https://github.com/wzshiming/custom-metrics-apiserver-simulator
