### ISSUE TITLE
custom-metrics-apiserver compile failed with k8s.io/apiserver v0.29.2

### ISSUE THREAD

**Issue by selamat** [kubernetes-sigs/custom-metrics-apiserver#167]
HI, my go application using
```
sigs.k8s.io/custom-metrics-apiserver v1.28.0
k8s.io/apiserver v0.29.2
```
and it can't compile succeed because of this function **func (o *CustomMetricsAdapterServerOptions) ApplyTo(serverConfig *genericapiserver.Config) error **.  In this function, it called _ApplyTo_  in package _k8s.io/apiserver_,  but in v0.29.2version,  _ApplyTo_ has 3 parameters.  Also I compare  _k8s.io/apiserver_  between v0.29 and v0.28,  in version0.28, _ApplyTo_ has only 1 parameter.

Maybe I think custom-metrics-apiserver should fit kubernetes v1.29

**Comment by RainbowMango** [comment]
cc @dgrisonnet

/help

**Comment by dgrisonnet** [comment]
Hi @selamat, yeah it sounds like we will need to bump the k8s dependencies to the latest ones so v1.29.3. I'll take care of it and publish a release soon.

/assign

**Comment by RainbowMango** [comment]
Yes, it is the v1.29.3.  Thank you @dabradley in advance.
