### ISSUE TITLE
Do we support container metric level now?

### ISSUE THREAD

**Issue by zoux86** [kubernetes-sigs/custom-metrics-apiserver#74]
k8s now support a new metric named ContainerResource metric

see https://github.com/kubernetes/kubernetes/pull/90691/files

so i want to know do we support it now? if not, how can i do to support it  in my our metric-provider?

**Comment by s-urbaniak** [comment]
The referenced PR implements container resource metrics which are already present as part of the Resource Metrics API. There is no need to implement it in custom metrics as they can be inferred from existing resource metrics (they are tracked per container already).
